# -*- coding: utf-8 -*-
"""lstmnextwordprediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwvR72xIhsKdKI341kzBjy-Qvvhb_KPf
"""

text = open("corpus.txt", encoding="utf-8").read().lower()

import re
text = re.sub(r'[^a-zA-Z\s]', '', text)

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1

from tensorflow.keras.preprocessing.sequence import pad_sequences
input_sequences = []
for line in text.split("\n"):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        input_sequences.append(token_list[:i+1])

max_len = max(len(x) for x in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

max_len

input_sequences

import numpy as np

X = input_sequences[:, :-1]
y = input_sequences[:, -1]

y = np.array(y)

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential([
    Embedding(total_words, 100, input_length=max_len-1),
    LSTM(150),
    Dense(total_words, activation='softmax')
])

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=128
)

model.save("model.h5")

import pickle
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

def predict_next_word(text, model, tokenizer, max_len):
    text = text.lower().strip()

    token_list = tokenizer.texts_to_sequences([text])[0]

    if len(token_list) == 0:
        return "[UNKNOWN]"

    token_list = pad_sequences(
        [token_list],
        maxlen=max_len - 1,
        padding='pre'
    )

    predictions = model.predict(token_list, verbose=0)
    predicted_index = np.argmax(predictions, axis=-1)[0]

    return tokenizer.index_word.get(predicted_index, "[UNKNOWN]")

text = "deep learning is"
next_word = predict_next_word(text, model, tokenizer, max_len)
print(f"Input: {text}")
print(f"Predicted next word: {next_word}")

test_sentences = [
    "machine learning is",
    "artificial intelligence can",
    "deep neural networks are",
    "the future of ai is",
    "data science helps"
]

for sentence in test_sentences:
    print(f"{sentence} → {predict_next_word(sentence, model, tokenizer, max_len)}")

